import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from "react-icons/ai";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Md Abdur Rahman Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-white px-10">
                <section className="min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between">
                        <h1 className="text-xl font-burtons">Portfolio</h1>
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill className="cursor-pointer" />
                            </li>
                            <li>
                                <a
                                    className="bg-gradient-to-r from-cyan-500
                                    to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8"
                                    href="#"
                                >
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div>
                        <h2>Md Abdur Rahman</h2>
                        <h3>Junior MERN Stack Web Developer</h3>
                        <p>
                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia vero
                            sapiente officiis sint doloremque odio dignissimos harum fugiat
                            molestias inventore.
                        </p>
                    </div>
                    <div>
                        <AiFillTwitterCircle />
                        <AiFillLinkedin />
                        <AiFillYoutube />
                    </div>
                </section>
            </main>
        </div>
    );
}
